# Generated by Django 6.0.3 on 2026-03-30 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilizador_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilizador_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_perfil', models.CharField(choices=[('Gestor', 'Gestor do Internato'), ('Financeiro', 'Administrador Financeiro'), ('Disciplinar', 'Responsável Disciplinar'), ('Suporte', 'Suporte Técnico'), ('Estudante', 'Estudante'), ('Encarregado', 'Encarregado')], max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('bloco', models.CharField(max_length=50)),
                ('capacidade_maxima', models.PositiveIntegerField()),
                ('genero_permitido', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Manutenção', 'Em Manutenção'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
                ('ocupacao_atual', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_completo', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('curso', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('bi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone_pessoal', models.CharField(blank=True, max_length=20, null=True)),
                ('email_pessoal', models.EmailField(blank=True, max_length=254, null=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('parentesco', models.CharField(blank=True, choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Tio', 'Tio/Tia'), ('Irmão', 'Irmão/Irmã'), ('Avô', 'Avô/Avó'), ('Outro', 'Outro')], max_length=20, null=True)),
                ('telefone_principal', models.CharField(max_length=20)),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bi', models.CharField(blank=True, max_length=20, null=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('utilizador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encarregado_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encarregado / Contacto de Emergência',
                'verbose_name_plural': 'Encarregados',
            },
        ),
        migrations.AddField(
            model_name='utilizador',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfil'),
        ),
        migrations.CreateModel(
            name='Sancao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sancao', models.CharField(choices=[('Advertência Verbal', 'Advertência Verbal'), ('Trabalho Comunitário', 'Trabalho Comunitário'), ('Suspensão de Saída', 'Suspensão de Saída'), ('Outro', 'Outro')], max_length=100)),
                ('data_ocorrencia', models.DateField()),
                ('descricao', models.TextField()),
                ('notificado_encarregado', models.BooleanField(default=False)),
                ('admin_id_registo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sancoes_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sancoes', to='core.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('data_saida_pretendida', models.DateField()),
                ('data_retorno_pretendida', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente (Aguarda Admin)'), ('Aguardando_Encarregado', 'Aprovado Admin — Aguarda Encarregado'), ('Autorizado', 'Autorizado — Aprovado por todos'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=30)),
                ('aprovado_por_sms', models.BooleanField(default=False)),
                ('token_sms', models.CharField(blank=True, max_length=6, null=True)),
                ('aprovado_presencialmente', models.BooleanField(default=False)),
                ('data_aprovacao_encarregado', models.DateTimeField(blank=True, null=True)),
                ('observacao_admin', models.TextField(blank=True, null=True)),
                ('data_saida_real', models.DateTimeField(blank=True, null=True)),
                ('data_regresso_real', models.DateTimeField(blank=True, null=True)),
                ('admin_id_aprovacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_saida', to='core.estudante')),
            ],
        ),
        migrations.AddField(
            model_name='estudante',
            name='encarregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='core.encarregado'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='core.quarto'),
        ),
        migrations.CreateModel(
            name='PresencaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField()),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Justificado', 'Justificado')], default='Presente', max_length=15)),
                ('admin_id_registo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_registadas', to=settings.AUTH_USER_MODEL)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.estudante')),
            ],
            options={
                'unique_together': {('estudante', 'data_presenca')},
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_pagamento_confirmado', models.DateField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('Depósito', 'Depósito'), ('Numerário', 'Numerário')], max_length=20, null=True)),
                ('referencia_comprovativo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=10)),
                ('data_vencimento', models.DateField(blank=True, help_text='Data de vencimento. Calculada automaticamente no save().', null=True)),
                ('numero_recibo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('arquivo_pdf_recibo', models.FileField(blank=True, null=True, upload_to='recibos/')),
                ('admin_id_registo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades_registadas', to=settings.AUTH_USER_MODEL)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='core.estudante')),
            ],
            options={
                'unique_together': {('estudante', 'mes_referencia')},
            },
        ),
    ]
