# Generated by Django 6.0.3 on 2026-03-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='recibos/')),
                ('mensalidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='core.mensalidade')),
            ],
        ),
    ]
