# Generated by Django 6.0.3 on 2026-03-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Acesso (estudantes)'),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone (encarregados)'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
