# Generated by Django 6.0.3 on 2026-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_utilizador_codigo_acesso_utilizador_telefone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presencaestudo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='encarregado',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='ano_lectivo',
            field=models.CharField(default='2025/2026', max_length=9, verbose_name='Ano Lectivo'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='condicao_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Condições de Saúde'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Moçambicana', max_length=50),
        ),
        migrations.AddField(
            model_name='estudante',
            name='nuit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NUIT'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='tipo',
            field=models.CharField(choices=[('Inscrição', 'Inscrição'), ('Mensalidade', 'Mensalidade')], default='Mensalidade', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='cidade_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='meio_transporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presencaestudo',
            name='periodo',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Manhã', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='presencaestudo',
            unique_together={('estudante', 'data_presenca', 'periodo')},
        ),
    ]
