# Generated by Django 5.2.8 on 2025-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_popular_perfis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sancao',
            name='tipo_sancao',
            field=models.CharField(choices=[('Advertência Verbal', 'Advertência Verbal'), ('Trabalho Comunitário', 'Trabalho Comunitário'), ('Suspensão de Saída', 'Suspensão de Saída'), ('Outro', 'Outro')], max_length=100),
        ),
    ]
