# Generated by Django 6.0.3 on 2026-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento da mensalidade', null=True),
        ),
    ]
