# Generated by Django 6.0.3 on 2026-06-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_presencaestudo_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='numero',
        ),
    ]
