# Generated by Django 6.0.3 on 2026-03-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensalidade_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='num_estudante',
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='arquivo_pdf_recibo',
            field=models.FileField(blank=True, null=True, upload_to='recibos/'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='data_regresso_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosaida',
            name='data_saida_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento. Calculada automaticamente no save().', null=True),
        ),
        migrations.AlterField(
            model_name='pedidosaida',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente (Aguarda Admin)'), ('Aguardando_Encarregado', 'Aprovado Admin — Aguarda Encarregado'), ('Autorizado', 'Autorizado — Aprovado por todos'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=30),
        ),
        migrations.DeleteModel(
            name='Recibo',
        ),
    ]
