# Generated by Django 6.0.2 on 2026-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sancao_tipo_sancao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaida',
            name='data_aprovacao_encarregado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosaida',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente (Admin)'), ('Aguardando_Encarregado', 'Aprovado Admin (Falta Encarregado)'), ('Autorizado', 'Autorizado (Final)'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=30),
        ),
    ]
