# Generated by Django 6.0.3 on 2026-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_quarto_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='perfis',
            field=models.ManyToManyField(blank=True, related_name='perfis_m2m', to='core.perfil'),
        ),
    ]
