# Generated by Django 6.0.3 on 2026-06-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_utilizador_perfis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='perfil',
        ),
    ]
