# Generated by Django 6.0.3 on 2026-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_utilizador_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='ano_lectivo',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
